### ISSUE TITLE
Fetch COG from cloud storage with presigned url failed

### ISSUE THREAD

**Issue by lawrencenika** [geomatico/maplibre-cog-protocol#10]
Thanks team for this library, it was working very well until I tried to pass in a presigned cloud storage object url that is referring to a COG stored in there, and it is not showing up in the maplibre map. 

This is the url structure I tried:

```
<Map style="xxx">
    <Source
        id='imageSource'
        type='raster'
        url='cog://https://storage.googleapis.com/bucket-object.tif?x-goog-signature=signature-hidden&x-goog-algorithm=GOOG4-RSA-SHA256&x-goog-credential=sa-hidden&x-goog-date=20240828T162541Z&x-goog-expires=3600&x-goog-signedheaders=host'
        tileSize={256}
    >
        <Layer id='imageLayer' type='raster' />
    </Source>
</Map>
```

is there any way to make it work?

**Comment by oscarfonts** [comment]
We have used presigned URLs from AWS S3 without problem, but haven't tested google storage APIs specifically.
Please try to narrow the cause of the problem and reopen if it has to do with some bug or missing feature here.
