### ISSUE TITLE
How to "style" the COG within the stylesheet/progmaticly instead of specifying in the URL

### ISSUE THREAD

**Issue by dBitech** [geomatico/maplibre-cog-protocol#15]
Can that even be done?  if so is there an example ?

In a nutshell I have a single band COG and I'd like to color all values between 0 and 187 green, 188 to 195 yellow, 196 to 200 red, and 201+ no color at all.  But when a user clicks a button, to change those breakpoints down by 10.  so 0-177,178-185,186-190,191+ .

**Comment by oscarfonts** [comment]
We cannot use the styling engine of Maplibre as that would imply changing Maplibre's code base.
So we have to hack in the style via the URL.

You can replace the url programmatically with Maplibre API: `map.getSource('myCog').setUrl(newUrl)`.

We have an example that dynamically changes the color ramp here:
https://labs.geomatico.es/maplibre-cog-protocol-examples/#/en/mediterraneo

But the color interpolation is always applied in equal intervals, which is not your case.

Keeping the issue open, as having a way to specify arbitrary ranges for a color scale would be a nice addition.

**Comment by dBitech** [comment]
I wonder if any of the ideas or efforts around [Is it possible to use terrain data in a custom style layer to shade the map?](https://github.com/maplibre/maplibre-gl-js/discussions/4133) could be corralled to bring this across the finish line

**Comment by oscarfonts** [comment]
Done.

See usage examples:

https://github.com/geomatico/maplibre-cog-protocol?tab=readme-ov-file#apply-a-custom-color-function-to-any-cog
https://github.com/geomatico/maplibre-cog-protocol/blob/main/MIGRATIONS.md#032-to-040
https://github.com/geomatico/maplibre-cog-protocol/blob/main/examples/custom-color.html#L65
