### ISSUE TITLE
COG Protocol fails to render valid small Cloud-Optimized GeoTIFF that displays correctly in Google Earth

### ISSUE THREAD

**Issue by earth-bass** [geomatico/maplibre-cog-protocol#17]
I have attached a visualization of how the cog looks in google earth
![image](https://github.com/user-attachments/assets/e638414c-5ed6-4794-9db8-8ccca398931b)

Here is the file if you want to reproduce the error:
https://drive.google.com/file/d/19i-qMuRTDLYqP2IrS_CFlWZSSG0Nrwnk/view?usp=sharing

**Comment by oscarfonts** [comment]
It will work if you reproject. Please read the [COG generation tips](https://github.com/geomatico/maplibre-cog-protocol?tab=readme-ov-file#cog-generation-tips?) section in README.md
